// 摄影作品列表：src 为原图（大图用），thumb 为压缩图（列表+动画用，统一 .jpg）
// 名称 = 文件名去掉扩展名；显示时按第一个空格分两行（第一行 0.8 字号，第二行 0.6 字号）
// 顺序：运行时按名称首字母（拼音）排列
window.PHOTOS_DATA = [
  { src: "photos/摄影作品/一舟 Nikon.jpg",               thumb: "photos/thumbs/一舟 Nikon.jpg",               caption: "一舟 Nikon" },
  { src: "photos/摄影作品/人像Ⅰ GR3.jpg",               thumb: "photos/thumbs/人像Ⅰ GR3.jpg",               caption: "人像Ⅰ GR3" },
  { src: "photos/摄影作品/人像Ⅱ Mobile phone.jpg",       thumb: "photos/thumbs/人像Ⅱ Mobile phone.jpg",       caption: "人像Ⅱ Mobile phone" },
  { src: "photos/摄影作品/人像Ⅲ Mobile phone.jpg",       thumb: "photos/thumbs/人像Ⅲ Mobile phone.jpg",       caption: "人像Ⅲ Mobile phone" },
  { src: "photos/摄影作品/人像Ⅳ Mobile phone.jpg",       thumb: "photos/thumbs/人像Ⅳ Mobile phone.jpg",       caption: "人像Ⅳ Mobile phone" },
  { src: "photos/摄影作品/人像Ⅴ Mobile phone.jpg",       thumb: "photos/thumbs/人像Ⅴ Mobile phone.jpg",       caption: "人像Ⅴ Mobile phone" },
  { src: "photos/摄影作品/人像Ⅵ GR3.JPG",               thumb: "photos/thumbs/人像Ⅵ GR3.jpg",               caption: "人像Ⅵ GR3" },
  { src: "photos/摄影作品/剪影Ⅰ Contax G1.jpg",         thumb: "photos/thumbs/剪影Ⅰ Contax G1.jpg",         caption: "剪影Ⅰ Contax G1" },
  { src: "photos/摄影作品/剪影Ⅱ Mobile phone.jpg",       thumb: "photos/thumbs/剪影Ⅱ Mobile phone.jpg",       caption: "剪影Ⅱ Mobile phone" },
  { src: "photos/摄影作品/午后 Contax G1.jpg",           thumb: "photos/thumbs/午后 Contax G1.jpg",           caption: "午后 Contax G1" },
  { src: "photos/摄影作品/向往 Contax G1.JPG",           thumb: "photos/thumbs/向往 Contax G1.jpg",           caption: "向往 Contax G1" },
  { src: "photos/摄影作品/困惑 Contax G1.JPG",           thumb: "photos/thumbs/困惑 Contax G1.jpg",           caption: "困惑 Contax G1" },
  { src: "photos/摄影作品/围栏 Contax G1.JPG",           thumb: "photos/thumbs/围栏 Contax G1.jpg",           caption: "围栏 Contax G1" },
  { src: "photos/摄影作品/夜摊 Pentax.JPG",              thumb: "photos/thumbs/夜摊 Pentax.jpg",              caption: "夜摊 Pentax" },
  { src: "photos/摄影作品/她和她 Mobile phone.jpg",       thumb: "photos/thumbs/她和她 Mobile phone.jpg",       caption: "她和她 Mobile phone" },
  { src: "photos/摄影作品/小憩 Contax G1.JPG",           thumb: "photos/thumbs/小憩 Contax G1.jpg",           caption: "小憩 Contax G1" },
  { src: "photos/摄影作品/影子 Mobile phone.jpg",         thumb: "photos/thumbs/影子 Mobile phone.jpg",         caption: "影子 Mobile phone" },
  { src: "photos/摄影作品/快艇 Contax G1.JPG",           thumb: "photos/thumbs/快艇 Contax G1.jpg",           caption: "快艇 Contax G1" },
  { src: "photos/摄影作品/捕梦网Ⅰ Contax G1.JPG",       thumb: "photos/thumbs/捕梦网Ⅰ Contax G1.jpg",       caption: "捕梦网Ⅰ Contax G1" },
  { src: "photos/摄影作品/捕梦网Ⅱ Contax G1.JPG",       thumb: "photos/thumbs/捕梦网Ⅱ Contax G1.jpg",       caption: "捕梦网Ⅱ Contax G1" },
  { src: "photos/摄影作品/捕梦网Ⅲ Mobile phone.jpg",     thumb: "photos/thumbs/捕梦网Ⅲ Mobile phone.jpg",     caption: "捕梦网Ⅲ Mobile phone" },
  { src: "photos/摄影作品/摇曳 Contax G1.JPG",           thumb: "photos/thumbs/摇曳 Contax G1.jpg",           caption: "摇曳 Contax G1" },
  { src: "photos/摄影作品/放风筝 Contax G1.JPG",         thumb: "photos/thumbs/放风筝 Contax G1.jpg",         caption: "放风筝 Contax G1" },
  { src: "photos/摄影作品/救生员 Contax G1.jpg",         thumb: "photos/thumbs/救生员 Contax G1.jpg",         caption: "救生员 Contax G1" },
  { src: "photos/摄影作品/木屋 Mobile phone.jpg",         thumb: "photos/thumbs/木屋 Mobile phone.jpg",         caption: "木屋 Mobile phone" },
  { src: "photos/摄影作品/杂草 Nikon.jpg",               thumb: "photos/thumbs/杂草 Nikon.jpg",               caption: "杂草 Nikon" },
  { src: "photos/摄影作品/枝上半月 Nikon.jpg",           thumb: "photos/thumbs/枝上半月 Nikon.jpg",           caption: "枝上半月 Nikon" },
  { src: "photos/摄影作品/栏杆87号 Mobile phone.jpg",     thumb: "photos/thumbs/栏杆87号 Mobile phone.jpg",     caption: "栏杆87号 Mobile phone" },
  { src: "photos/摄影作品/树隙 Nikon.JPG",               thumb: "photos/thumbs/树隙 Nikon.jpg",               caption: "树隙 Nikon" },
  { src: "photos/摄影作品/泳圈 Contax G1.JPG",           thumb: "photos/thumbs/泳圈 Contax G1.jpg",           caption: "泳圈 Contax G1" },
  { src: "photos/摄影作品/磨砂 Contax G1.jpg",           thumb: "photos/thumbs/磨砂 Contax G1.jpg",           caption: "磨砂 Contax G1" },
  { src: "photos/摄影作品/礁石乐场Ⅰ Contax G1.JPG",     thumb: "photos/thumbs/礁石乐场Ⅰ Contax G1.jpg",     caption: "礁石乐场Ⅰ Contax G1" },
  { src: "photos/摄影作品/礁石乐场Ⅱ Contax G1.JPG",     thumb: "photos/thumbs/礁石乐场Ⅱ Contax G1.jpg",     caption: "礁石乐场Ⅱ Contax G1" },
  { src: "photos/摄影作品/礁石乐场Ⅲ Contax G1.JPG",     thumb: "photos/thumbs/礁石乐场Ⅲ Contax G1.jpg",     caption: "礁石乐场Ⅲ Contax G1" },
  { src: "photos/摄影作品/礁石乐场Ⅳ Contax G1.JPG",     thumb: "photos/thumbs/礁石乐场Ⅳ Contax G1.jpg",     caption: "礁石乐场Ⅳ Contax G1" },
  { src: "photos/摄影作品/空间 Mobile phone.JPG",         thumb: "photos/thumbs/空间 Mobile phone.jpg",         caption: "空间 Mobile phone" },
  { src: "photos/摄影作品/窗边光 Pentax.jpg",             thumb: "photos/thumbs/窗边光 Pentax.jpg",             caption: "窗边光 Pentax" },
  { src: "photos/摄影作品/竹蜻蜓 Nikon.jpg",             thumb: "photos/thumbs/竹蜻蜓 Nikon.jpg",             caption: "竹蜻蜓 Nikon" },
  { src: "photos/摄影作品/绿色尽头 Mobile phone.jpg",     thumb: "photos/thumbs/绿色尽头 Mobile phone.jpg",     caption: "绿色尽头 Mobile phone" },
  { src: "photos/摄影作品/足球 Mobile phone.JPG",         thumb: "photos/thumbs/足球 Mobile phone.jpg",         caption: "足球 Mobile phone" },
  { src: "photos/摄影作品/路人Ⅰ Mobile phone.JPG",       thumb: "photos/thumbs/路人Ⅰ Mobile phone.jpg",       caption: "路人Ⅰ Mobile phone" },
  { src: "photos/摄影作品/路人Ⅱ GR3.jpg",               thumb: "photos/thumbs/路人Ⅱ GR3.jpg",               caption: "路人Ⅱ GR3" },
  { src: "photos/摄影作品/路人Ⅲ Mobile phone.jpg",       thumb: "photos/thumbs/路人Ⅲ Mobile phone.jpg",       caption: "路人Ⅲ Mobile phone" },
  { src: "photos/摄影作品/路人Ⅳ Mobile phone.jpg",       thumb: "photos/thumbs/路人Ⅳ Mobile phone.jpg",       caption: "路人Ⅳ Mobile phone" },
  { src: "photos/摄影作品/路人Ⅴ Mobile phone.jpg",       thumb: "photos/thumbs/路人Ⅴ Mobile phone.jpg",       caption: "路人Ⅴ Mobile phone" },
  { src: "photos/摄影作品/跳水 Contax G1.JPG",           thumb: "photos/thumbs/跳水 Contax G1.jpg",           caption: "跳水 Contax G1" },
  { src: "photos/摄影作品/车窗内Ⅰ GR3.jpeg",            thumb: "photos/thumbs/车窗内Ⅰ GR3.jpg",             caption: "车窗内Ⅰ GR3" },
  { src: "photos/摄影作品/车窗内Ⅱ Mobile phone.jpg",     thumb: "photos/thumbs/车窗内Ⅱ Mobile phone.jpg",     caption: "车窗内Ⅱ Mobile phone" },
  { src: "photos/摄影作品/车窗内Ⅲ Mobile phone.jpg",     thumb: "photos/thumbs/车窗内Ⅲ Mobile phone.jpg",     caption: "车窗内Ⅲ Mobile phone" },
  { src: "photos/摄影作品/车窗内Ⅳ GR3.jpg",             thumb: "photos/thumbs/车窗内Ⅳ GR3.jpg",             caption: "车窗内Ⅳ GR3" },
  { src: "photos/摄影作品/车窗内Ⅴ Nikon.JPG",           thumb: "photos/thumbs/车窗内Ⅴ Nikon.jpg",           caption: "车窗内Ⅴ Nikon" },
  { src: "photos/摄影作品/逆光Ⅰ Nikon.jpg",             thumb: "photos/thumbs/逆光Ⅰ Nikon.jpg",             caption: "逆光Ⅰ Nikon" },
  { src: "photos/摄影作品/逆光Ⅱ Nikon.jpg",             thumb: "photos/thumbs/逆光Ⅱ Nikon.jpg",             caption: "逆光Ⅱ Nikon" },
  { src: "photos/摄影作品/逆光Ⅲ GR3.JPG",               thumb: "photos/thumbs/逆光Ⅲ GR3.jpg",               caption: "逆光Ⅲ GR3" },
  { src: "photos/摄影作品/逆光Ⅳ GR3.JPG",               thumb: "photos/thumbs/逆光Ⅳ GR3.jpg",               caption: "逆光Ⅳ GR3" },
  { src: "photos/摄影作品/逆光Ⅴ GR3.jpg",               thumb: "photos/thumbs/逆光Ⅴ GR3.jpg",               caption: "逆光Ⅴ GR3" },
  { src: "photos/摄影作品/逆光Ⅵ GR3.jpg",               thumb: "photos/thumbs/逆光Ⅵ GR3.jpg",               caption: "逆光Ⅵ GR3" },
  { src: "photos/摄影作品/遮阳 Contax G1.jpg",           thumb: "photos/thumbs/遮阳 Contax G1.jpg",           caption: "遮阳 Contax G1" },
  { src: "photos/摄影作品/阴影 Contax G1.jpg",           thumb: "photos/thumbs/阴影 Contax G1.jpg",           caption: "阴影 Contax G1" },
  { src: "photos/摄影作品/雕塑 Mobile phone.jpg",         thumb: "photos/thumbs/雕塑 Mobile phone.jpg",         caption: "雕塑 Mobile phone" },
  { src: "photos/摄影作品/雨镜 Contax G1.JPG",           thumb: "photos/thumbs/雨镜 Contax G1.jpg",           caption: "雨镜 Contax G1" },
  { src: "photos/摄影作品/雪Ⅰ GR3.JPG",                 thumb: "photos/thumbs/雪Ⅰ GR3.jpg",                 caption: "雪Ⅰ GR3" },
  { src: "photos/摄影作品/雪Ⅱ GR3.jpg",                 thumb: "photos/thumbs/雪Ⅱ GR3.jpg",                 caption: "雪Ⅱ GR3" },
  { src: "photos/摄影作品/雪Ⅲ GR3.JPG",                 thumb: "photos/thumbs/雪Ⅲ GR3.jpg",                 caption: "雪Ⅲ GR3" },
  { src: "photos/摄影作品/飞鸟 Mobile phone.JPG",         thumb: "photos/thumbs/飞鸟 Mobile phone.jpg",         caption: "飞鸟 Mobile phone" },
];

// 按名称首字母（拼音）顺序排列
window.PHOTOS_DATA = window.PHOTOS_DATA.sort(function (a, b) {
  return a.caption.localeCompare(b.caption, "zh-CN");
});
